export enum TransactionType {
  INCOME = "INCOME",
  EXPENSE = "EXPENSE",
  TRANSFER = "TRANSFER"
}

export enum WalletRole {
  ADMIN = "ADMIN",
  EDITOR = "EDITOR",
  VIEWER = "VIEWER"
}

export enum UserRole {
  ADMIN = "ADMIN",
  MEMBER = "MEMBER"
}

export enum SyncEventType {
  TRANSACTION_CREATED = "TRANSACTION_CREATED",
  TRANSACTION_UPDATED = "TRANSACTION_UPDATED",
  TRANSACTION_DELETED = "TRANSACTION_DELETED"
}
